
/* Includes added by #pragma extra_include */
#include "vector"
#include "string"
#include "map"
/********************************************************************
* myDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error myDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "cint/G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtablemyDict();
extern void G__cpp_setup_inheritancemyDict();
extern void G__cpp_setup_typetablemyDict();
extern void G__cpp_setup_memvarmyDict();
extern void G__cpp_setup_globalmyDict();
extern void G__cpp_setup_memfuncmyDict();
extern void G__cpp_setup_funcmyDict();
extern void G__set_cpp_environmentmyDict();
}


#include "TObject.h"
#include "TMemberInspector.h"

#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__myDictLN_ROOT;
extern G__linked_taginfo G__myDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__myDictLN_string;
extern G__linked_taginfo G__myDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__myDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__myDictLN_lesslEstringgR;
extern G__linked_taginfo G__myDictLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR;
extern G__linked_taginfo G__myDictLN_ROOTcLcLMath;
extern G__linked_taginfo G__myDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__myDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__myDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__myDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__myDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__myDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__myDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__myDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__myDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__myDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__myDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__myDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__myDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__myDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__myDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__myDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__myDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__myDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__myDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__myDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__myDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__myDictLN_ROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPxPyPzE4DlEdoublegRsPgR;
extern G__linked_taginfo G__myDictLN_vectorlEROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPxPyPzE4DlEdoublegRsPgRcOallocatorlEROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPxPyPzE4DlEdoublegRsPgRsPgRsPgR;
extern G__linked_taginfo G__myDictLN_vectorlEROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPxPyPzE4DlEdoublegRsPgRcOallocatorlEROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPxPyPzE4DlEdoublegRsPgRsPgRsPgRcLcLiterator;
extern G__linked_taginfo G__myDictLN_reverse_iteratorlEvectorlEROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPxPyPzE4DlEdoublegRsPgRcOallocatorlEROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPxPyPzE4DlEdoublegRsPgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__myDictLN_pairlEconstsPstringcOboolgR;
extern G__linked_taginfo G__myDictLN_allocatorlEpairlEconstsPstringcOboolgRsPgR;
extern G__linked_taginfo G__myDictLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR;
extern G__linked_taginfo G__myDictLN_pairlEstringcOboolgR;
extern G__linked_taginfo G__myDictLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgRcLcLiterator;
extern G__linked_taginfo G__myDictLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__myDictLN_pairlEmaplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgRcLcLiteratorcOboolgR;
extern G__linked_taginfo G__myDictLN_pairlEconstsPstringcOvectorlEfloatcOallocatorlEfloatgRsPgRsPgR;
extern G__linked_taginfo G__myDictLN_allocatorlEpairlEconstsPstringcOvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR;
extern G__linked_taginfo G__myDictLN_maplEstringcOvectorlEfloatcOallocatorlEfloatgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__myDictLN_pairlEstringcOvectorlEfloatcOallocatorlEfloatgRsPgRsPgR;
extern G__linked_taginfo G__myDictLN_maplEstringcOvectorlEfloatcOallocatorlEfloatgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRsPgRcLcLiterator;
extern G__linked_taginfo G__myDictLN_maplEstringcOvectorlEfloatcOallocatorlEfloatgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__myDictLN_pairlEmaplEstringcOvectorlEfloatcOallocatorlEfloatgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRsPgRcLcLiteratorcOboolgR;

/* STUB derived class for protected member access */
typedef vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> >,allocator<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> > > > G__vectorlEROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPxPyPzE4DlEdoublegRsPgRcOallocatorlEROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPxPyPzE4DlEdoublegRsPgRsPgRsPgR;
typedef vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> >,allocator<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<double> > > >::iterator G__vectorlEROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPxPyPzE4DlEdoublegRsPgRcOallocatorlEROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPxPyPzE4DlEdoublegRsPgRsPgRsPgRcLcLiterator;
typedef pair<const string,bool> G__pairlEconstsPstringcOboolgR;
typedef map<string,bool,less<string>,allocator<pair<const string,bool> > > G__maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR;
typedef pair<string,bool> G__pairlEstringcOboolgR;
typedef map<string,bool,less<string>,allocator<pair<const string,bool> > >::iterator G__maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgRcLcLiterator;
typedef pair<const string,vector<float,allocator<float> > > G__pairlEconstsPstringcOvectorlEfloatcOallocatorlEfloatgRsPgRsPgR;
typedef map<string,vector<float,allocator<float> >,less<string>,allocator<pair<const string,vector<float,allocator<float> > > > > G__maplEstringcOvectorlEfloatcOallocatorlEfloatgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRsPgR;
typedef pair<string,vector<float,allocator<float> > > G__pairlEstringcOvectorlEfloatcOallocatorlEfloatgRsPgRsPgR;
typedef map<string,vector<float,allocator<float> >,less<string>,allocator<pair<const string,vector<float,allocator<float> > > > >::iterator G__maplEstringcOvectorlEfloatcOallocatorlEfloatgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRsPgRcLcLiterator;
